apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev
  chart:
    repository: https://marclamberti.github.io/airflow-eks-helm-chart
    name: airflow
    version: 7.1.0
  values:
    airflow:
        fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
        config:
            AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
            AIRFLOW__KUBERNETES__NAMESPACE: "dev"
            AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "018079024734.dkr.ecr.us-east-1.amazonaws.com/airflow-chethan"
            AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "latest"
            AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
        executor: KubernetesExecutor
        image:
            repository: 018079024734.dkr.ecr.us-east-1.amazonaws.com/airflow-chethan
            tag: latest