apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev
  chart:
    repository: https://marclamberti.github.io/airflow-eks-helm-chart
    name: airflow
    version: 1.0.0
  values:
    images:
      airflow:
        repository: "018079024734.dkr.ecr.us-east-1.amazonaws.com/airflow-chethan"
        tag: "latest"
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE"
        value: "True"
      - name: "AIRFLOW__KUBERNETES__NAMESPACE"
        value: "dev"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY"
        value: "018079024734.dkr.ecr.us-east-1.amazonaws.com/airflow-chethan"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG"
        value: "latest"
      - name: "AIRFLOW__KUBERNETES__RUN_AS_USER"
        value: "50000"
      - name: "AIRFLOW__KUBERNETES__GIT_SYNC_RUN_AS_USER"
        value: "65533"
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "False"
    executor: "KubernetesExecutor"